import { useEffect, useState } from 'react';

export type ModelSettings = {
  model: string;
  temperature: number;
  maxTokens: number;
};

export type SettingsPanelProps = {
  settings: ModelSettings;
  onChange: (settings: ModelSettings) => void;
};

function SettingsPanel({ settings, onChange }: SettingsPanelProps) {
  const [localSettings, setLocalSettings] = useState(settings);

  useEffect(() => {
    setLocalSettings(settings);
  }, [settings]);

  const updateSettings = (partial: Partial<ModelSettings>) => {
    const updated = { ...localSettings, ...partial };
    setLocalSettings(updated);
    onChange(updated);
  };

  return (
    <aside className="w-80 border-l border-gray-200 bg-gray-50 p-6 dark:border-gray-800 dark:bg-gray-950">
      <h2 className="mb-4 text-lg font-semibold text-gray-900 dark:text-gray-100">Model settings</h2>
      <div className="space-y-4 text-sm text-gray-700 dark:text-gray-200">
        <label className="block">
          <span className="mb-1 block text-xs uppercase tracking-wide text-gray-500">Model</span>
          <input
            type="text"
            value={localSettings.model}
            onChange={(event) => updateSettings({ model: event.target.value })}
            className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-primary focus:outline-none dark:border-gray-700 dark:bg-gray-900"
            placeholder="llama2"
          />
        </label>
        <label className="block">
          <span className="mb-1 block text-xs uppercase tracking-wide text-gray-500">Temperature</span>
          <input
            type="number"
            step="0.1"
            min="0"
            max="2"
            value={localSettings.temperature}
            onChange={(event) => updateSettings({ temperature: Number(event.target.value) })}
            className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-primary focus:outline-none dark:border-gray-700 dark:bg-gray-900"
          />
        </label>
        <label className="block">
          <span className="mb-1 block text-xs uppercase tracking-wide text-gray-500">Max tokens</span>
          <input
            type="number"
            min="64"
            max="4096"
            value={localSettings.maxTokens}
            onChange={(event) => updateSettings({ maxTokens: Number(event.target.value) })}
            className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-primary focus:outline-none dark:border-gray-700 dark:bg-gray-900"
          />
        </label>
        <div className="rounded-md bg-white p-3 text-xs text-gray-600 shadow-inner dark:bg-gray-900 dark:text-gray-300">
          <p className="font-semibold">Tips</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Ensure the model name matches one installed with Ollama (e.g., <code>llama2</code>).</li>
            <li>Higher temperature increases creativity but may reduce accuracy.</li>
            <li>Max tokens controls the length of responses generated by the model.</li>
          </ul>
        </div>
      </div>
    </aside>
  );
}

export default SettingsPanel;
